#!/usr/bin/env bash

install_list=make,gcc,cython3

dagger -c "
  container |
  from python:3.11 |
  with-exec apt-get,update |
  with-exec apt-get,install,-y,$install_list |
  with-directory "/app" /cython_scripts/example3 |
  with-workdir "/app" |
  terminal
"
